### ISSUE TITLE
Can MySQL and Oracle support that?

### ISSUE THREAD

**Issue by ghd258** [Chavoshi/EnterpriseLibrary.NetCore#2]
Can MySQL and Oracle support that?

**Comment by ghd258** [comment]
There are relevant examples

**Comment by Chavoshi** [comment]
MySql yes but Oracle not yet (because oracle client is not ported to .Net Core yet but we are working on it to find a third-party factory).

For MySql, I've committed an example for you here: https://github.com/Chavoshi/EnterpriseLibrary.NetCore/tree/master/Examples/EnterpriseLibrary.Test.MySql

P.S 1: You have to use MySql.Data version 8.0.8-dmr which is a per-release version 
P.S 2: You have to add 'system.data' config.section in your application configuration file like this:

<section name="system.data" type="System.Data.Common.DbProviderFactoriesConfigurationHandler, Microsoft.Practices.EnterpriseLibrary.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null"/>

The reason is 'DbProviderFactories' and 'DbProviderFactoriesConfigurationHandler' haven't ported yet and I've ported them by myself and put them in 'Microsoft.Practices.EnterpriseLibrary.Data'.
