### ISSUE TITLE
web.config and NetCore WebApp

### ISSUE THREAD

**Issue by jrocha** [Chavoshi/EnterpriseLibrary.NetCore#28]
Looks like `Microsoft.Practices.EnterpriseLibrary.Common.Configuration.SystemConfigurationSource`  is not behaving correctly when you are running on NetCore environment. 

The method `SafeGetCurrentConfigurationFile` is not returing the `web.config`.

**Comment by Chavoshi** [comment]
@jrocha,
As you know the ASP.NET Core web applications are hosed in a console application, it means when EntLib is going to load the config file, it tries to load the console's configuration file, so in order to make the EntLib work, add a application configuration file with name of app.config in the root of you project and put your EntLib configs inside that.

**Comment by jrocha** [comment]
It worked like a charm! Thanks!

**Comment by Chavoshi** [comment]
Anytime

**Comment by mgalvarez1187** [comment]
Thanks a lot! 
This helped me out! 
just as a note, I had to add this in the app.config file 
<configSections>
         <section name="dataConfiguration" 
      type="Microsoft.Practices.EnterpriseLibrary.Data.Configuration.DatabaseSettings, 
            Microsoft.Practices.EnterpriseLibrary.Data"/>
    </configSections>

and then, this in the data access class: 
DatabaseProviderFactory factory = new DatabaseProviderFactory();
 db = factory.Create("dProvider");

(see https://stackoverflow.com/questions/27763838/microsoft-practices-enterpriselibrary-data-dll-but-was-not-handled-in-user-code)

kind regards
