### ISSUE TITLE
Why the TargetFramework is netcoreapp2.0 and not netstandard2.0?

### ISSUE THREAD

**Issue by MonDeveloper** [Chavoshi/EnterpriseLibrary.NetCore#7]
Hi @Chavoshi , I'm wondering if there are any reason to targetting the package to netcoreapp and not to netstandard, could you help me understanding the reason?

**Comment by Chavoshi** [comment]
Sorry for the delay as I was a lot busy with the projects.
Yes you are right.
All the packages converted to .Net Standard.

The reason that I created them as .Net Core at the beginning was because I thought if someone wants to use it for .Net Framework, he uses the Microsoft stable version not this version.

BTW now ll the packages converted to .Net Standard.

**Comment by aristotelos** [comment]
I still get the following error:
```
NU1202: Package EnterpriseLibrary.Caching.NetCore 5.0.505 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package EnterpriseLibrary.Caching.NetCore 5.0.505 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
```
